/**
 * Canonical RBAC catalog — keep aligned with backendphase2/src/modules/role/default-permissions.js
 */
export type PermissionSeed = {
  permissionName: string;
  module: string;
  description: string;
};

export const RBAC_PERMISSION_SEED: PermissionSeed[] = [
  { permissionName: 'leads_create', module: 'Leads', description: 'Create leads' },
  { permissionName: 'leads_read', module: 'Leads', description: 'View leads' },
  { permissionName: 'leads_update', module: 'Leads', description: 'Update leads' },
  { permissionName: 'leads_delete', module: 'Leads', description: 'Delete leads' },
  { permissionName: 'view_all_leads', module: 'Leads', description: 'View all leads in tenant' },
  { permissionName: 'clients_create', module: 'Clients', description: 'Create clients' },
  { permissionName: 'clients_read', module: 'Clients', description: 'View clients' },
  { permissionName: 'clients_update', module: 'Clients', description: 'Update clients' },
  { permissionName: 'clients_delete', module: 'Clients', description: 'Delete clients' },
  { permissionName: 'view_all_clients', module: 'Clients', description: 'View all clients in tenant' },
  { permissionName: 'clients_handoff', module: 'Clients', description: 'Hand off clients to another department' },
  { permissionName: 'jobs_create', module: 'Jobs', description: 'Create jobs' },
  { permissionName: 'jobs_read', module: 'Jobs', description: 'View jobs' },
  { permissionName: 'jobs_update', module: 'Jobs', description: 'Update jobs' },
  { permissionName: 'jobs_delete', module: 'Jobs', description: 'Delete jobs' },
  { permissionName: 'assign_job', module: 'Jobs', description: 'Assign jobs to recruiters' },
  { permissionName: 'view_all_jobs', module: 'Jobs', description: 'View all jobs in tenant' },
  { permissionName: 'candidates_create', module: 'Candidates', description: 'Create candidates' },
  { permissionName: 'candidates_read', module: 'Candidates', description: 'View candidates' },
  { permissionName: 'candidates_update', module: 'Candidates', description: 'Update candidates' },
  { permissionName: 'candidates_delete', module: 'Candidates', description: 'Delete candidates' },
  { permissionName: 'view_all_candidates', module: 'Candidates', description: 'View all candidates in tenant' },
  { permissionName: 'view_assigned_candidates', module: 'Candidates', description: 'View only assigned candidates' },
  { permissionName: 'move_pipeline', module: 'Candidates', description: 'Move candidates in pipeline' },
  { permissionName: 'submit_candidate', module: 'Candidates', description: 'Submit candidates to jobs' },
  { permissionName: 'interviews_create', module: 'Interviews', description: 'Schedule interviews' },
  { permissionName: 'interviews_read', module: 'Interviews', description: 'View interviews' },
  { permissionName: 'interviews_update', module: 'Interviews', description: 'Update interviews' },
  { permissionName: 'interviews_delete', module: 'Interviews', description: 'Cancel or delete interviews' },
  { permissionName: 'placements_create', module: 'Placements', description: 'Create placements' },
  { permissionName: 'placements_read', module: 'Placements', description: 'View placements' },
  { permissionName: 'placements_update', module: 'Placements', description: 'Update placements' },
  { permissionName: 'placements_delete', module: 'Placements', description: 'Delete placements' },
  { permissionName: 'contacts_create', module: 'Contacts', description: 'Create contacts' },
  { permissionName: 'contacts_read', module: 'Contacts', description: 'View contacts' },
  { permissionName: 'contacts_update', module: 'Contacts', description: 'Update contacts' },
  { permissionName: 'contacts_delete', module: 'Contacts', description: 'Delete contacts' },
  { permissionName: 'tasks_create', module: 'Tasks', description: 'Create tasks' },
  { permissionName: 'tasks_read', module: 'Tasks', description: 'View tasks' },
  { permissionName: 'tasks_update', module: 'Tasks', description: 'Update tasks' },
  { permissionName: 'tasks_delete', module: 'Tasks', description: 'Delete tasks' },
  { permissionName: 'pipeline_read', module: 'Pipeline', description: 'View pipeline boards' },
  { permissionName: 'pipeline_manage', module: 'Pipeline', description: 'Move stages and manage pipeline' },
  { permissionName: 'matches_read', module: 'Matches', description: 'View candidate–job matches' },
  { permissionName: 'matches_manage', module: 'Matches', description: 'Save, submit, or reject matches' },
  { permissionName: 'agreements_read', module: 'Agreements', description: 'View agreements' },
  { permissionName: 'agreements_manage', module: 'Agreements', description: 'Create or update agreements' },
  { permissionName: 'inbox_read', module: 'Inbox', description: 'View inbox messages' },
  { permissionName: 'inbox_manage', module: 'Inbox', description: 'Send and manage inbox messages' },
  { permissionName: 'calendar_read', module: 'Calendar', description: 'View calendar' },
  { permissionName: 'calendar_manage', module: 'Calendar', description: 'Create or edit calendar events' },
  { permissionName: 'reports_create', module: 'Reports / Analytics', description: 'Create custom reports' },
  { permissionName: 'reports_read', module: 'Reports / Analytics', description: 'View reports and analytics' },
  { permissionName: 'reports_update', module: 'Reports / Analytics', description: 'Update reports' },
  { permissionName: 'reports_delete', module: 'Reports / Analytics', description: 'Delete reports' },
  { permissionName: 'access_billing', module: 'Billing', description: 'Access billing module' },
  { permissionName: 'create_invoice', module: 'Billing', description: 'Create and send invoices' },
  { permissionName: 'record_payment', module: 'Billing', description: 'Record payments' },
  { permissionName: 'manage_billing_settings', module: 'Billing', description: 'Manage billing settings' },
  { permissionName: 'view_team', module: 'Team', description: 'View team directory' },
  { permissionName: 'add_team_member', module: 'Team', description: 'Add team members' },
  { permissionName: 'edit_team_member', module: 'Team', description: 'Edit or deactivate team members' },
  { permissionName: 'assign_roles', module: 'Team', description: 'Assign roles to members' },
  { permissionName: 'manage_roles', module: 'Team', description: 'Create and edit roles & permissions' },
  { permissionName: 'generate_credentials', module: 'Team', description: 'Generate login credentials' },
  { permissionName: 'manage_commission', module: 'Team', description: 'Manage commission rules' },
  { permissionName: 'manage_targets', module: 'Team', description: 'Manage recruiter targets' },
  { permissionName: 'view_team_activity', module: 'Team', description: 'View team login and activity logs' },
  { permissionName: 'requests_create', module: 'Request', description: 'Send requests' },
  { permissionName: 'requests_read', module: 'Request', description: 'View requests' },
  { permissionName: 'requests_update', module: 'Request', description: 'Update request status' },
  { permissionName: 'requests_delete', module: 'Request', description: 'Cancel or delete requests' },
  { permissionName: 'view_all_requests', module: 'Request', description: 'View all requests in tenant' },
  { permissionName: 'manage_settings', module: 'System', description: 'Manage organization settings' },
  { permissionName: 'access_integrations', module: 'System', description: 'Access integrations' },
  { permissionName: 'export_data', module: 'System', description: 'Export data to CSV or files' },
  { permissionName: 'view_activity_log', module: 'System', description: 'View company activity feed' },
  { permissionName: 'recycle_bin_manage', module: 'System', description: 'Restore or purge recycle bin items' },
  { permissionName: 'view_dashboard', module: 'System', description: 'View main dashboard' },
  {
    permissionName: 'dash_full_scope',
    module: 'System',
    description:
      'Complete dashboard stats: see all records on allowed CRM/Recruitment tabs. Rank 1 and Super Admin already have this. Tick for a Rank 2+ deputy.',
  },
  {
    permissionName: 'dash_mine_approvals',
    module: 'System',
    description:
      'My work: include the approvals bucket (team requests, task completion, lead conversion, cross-dept). Super Admin and Rank 1 have this on by default. Tick for other roles that have Approvals / request / task permissions.',
  },
  { permissionName: 'dash_crm_insights', module: 'CRM Dashboard', description: 'CRM dashboard tab: Insights & actions' },
  { permissionName: 'dash_crm_pipeline', module: 'CRM Dashboard', description: 'CRM dashboard tab: Pipeline & records' },
  { permissionName: 'dash_crm_team', module: 'CRM Dashboard', description: 'CRM dashboard tab: Team & outreach' },
  { permissionName: 'dash_crm_people', module: 'CRM Dashboard', description: 'CRM dashboard tab: Hours & scores' },
  { permissionName: 'dash_rec_insights', module: 'Recruitment Dashboard', description: 'Recruitment dashboard tab: Insights & actions' },
  { permissionName: 'dash_rec_pipeline', module: 'Recruitment Dashboard', description: 'Recruitment dashboard tab: Pipeline & records' },
  { permissionName: 'dash_rec_team', module: 'Recruitment Dashboard', description: 'Recruitment dashboard tab: Team & performance' },
  { permissionName: 'dash_rec_people', module: 'Recruitment Dashboard', description: 'Recruitment dashboard tab: Hours & scores' },
];

export const RBAC_MODULE_ORDER = [
  'Leads',
  'Clients',
  'Jobs',
  'Candidates',
  'Interviews',
  'Placements',
  'Contacts',
  'Tasks',
  'Pipeline',
  'Matches',
  'Agreements',
  'Inbox',
  'Calendar',
  'Reports / Analytics',
  'Billing',
  'Team',
  'Request',
  'System',
  'CRM Dashboard',
  'Recruitment Dashboard',
] as const;

export const RBAC_CATALOG_TOTAL = RBAC_PERMISSION_SEED.length;
