const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

function daysAgo(n) {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d;
}

const jobs = [
  {
    title: "Full Stack Developer",
    location: "Bangalore, India", department: "Engineering", industry: "IT Services", isActive: true,
    overview: "Build scalable web apps across frontend and backend.",
    aboutRole: "Join our product squad to build and ship features used by millions.",
    description: "We are looking for a Full Stack Developer proficient in React and Node.js to join our growing engineering team.",
    keyResponsibilities: ["Develop React components", "Build REST APIs with Node.js", "Write unit tests", "Participate in code reviews", "Optimize database queries"],
    responsibilities: "Design, develop and maintain web applications.",
    skills: ["React", "Node.js", "MongoDB", "Express.js", "REST APIs"],
    preferredSkills: ["TypeScript", "Docker", "Redis"],
    experienceRequired: "2-5 Years", experienceLevel: "Mid", education: "B.Tech in Computer Science or related field",
    type: "FULL_TIME", employmentType: "FULL_TIME", workMode: "HYBRID",
    priority: "High",
    salary: { min: 800000, max: 1400000, currentCurrency: "INR" },
    salaryMin: 800000, salaryMax: 1400000, salaryCurrency: "INR", salaryType: "ANNUAL",
    benefits: ["Health Insurance", "Stock Options", "Flexible Hours", "Learning Budget"],
    visaSponsorship: false, postedAt: daysAgo(3), updatedAt: daysAgo(1),
  },
  {
    title: "Frontend Developer",
    location: "Remote", department: "Engineering", industry: "IT Services", isActive: true,
    overview: "Craft pixel-perfect UIs for our SaaS platform.",
    aboutRole: "Work closely with designers to build a world-class product interface.",
    description: "Seeking a passionate Frontend Developer with strong React and TypeScript skills.",
    keyResponsibilities: ["Build reusable React components", "Integrate REST APIs", "Ensure mobile responsiveness", "Optimize Core Web Vitals", "Write Storybook stories"],
    responsibilities: "Own the frontend layer of our web application.",
    skills: ["React", "TypeScript", "Tailwind CSS", "Next.js", "HTML5"],
    preferredSkills: ["GraphQL", "Storybook", "Figma", "Framer Motion"],
    experienceRequired: "1-4 Years", experienceLevel: "Junior", education: "Bachelor's Degree in any discipline",
    type: "FULL_TIME", employmentType: "FULL_TIME", workMode: "REMOTE",
    priority: "Regular",
    salary: { min: 600000, max: 1200000, currentCurrency: "INR" },
    salaryMin: 600000, salaryMax: 1200000, salaryCurrency: "INR", salaryType: "ANNUAL",
    benefits: ["Health Insurance", "Home Office Stipend", "Annual Bonus", "Paid Time Off"],
    visaSponsorship: false, postedAt: daysAgo(5), updatedAt: daysAgo(2),
  },
  {
    title: "Backend Developer",
    location: "Hyderabad, India", department: "Engineering", industry: "IT Services", isActive: true,
    overview: "Design and build robust server-side services.",
    aboutRole: "Own the architecture of core backend microservices that power our platform.",
    description: "Looking for a Backend Developer with deep expertise in Node.js, PostgreSQL, and cloud services.",
    keyResponsibilities: ["Design microservices", "Build REST and gRPC APIs", "Implement Redis caching", "Optimize SQL queries", "Monitor production services"],
    responsibilities: "Build and maintain reliable backend services.",
    skills: ["Node.js", "Express.js", "PostgreSQL", "REST APIs", "Docker"],
    preferredSkills: ["Kubernetes", "Redis", "RabbitMQ", "AWS"],
    experienceRequired: "3-6 Years", experienceLevel: "Senior", education: "B.Tech / B.E. in Engineering",
    type: "FULL_TIME", employmentType: "FULL_TIME", workMode: "ON_SITE",
    priority: "Urgent",
    salary: { min: 1200000, max: 2000000, currentCurrency: "INR" },
    salaryMin: 1200000, salaryMax: 2000000, salaryCurrency: "INR", salaryType: "ANNUAL",
    benefits: ["Health Insurance", "Performance Bonus", "Stock Options", "Gym Membership"],
    visaSponsorship: false, postedAt: daysAgo(2), updatedAt: daysAgo(1),
  },
  {
    title: "DevOps Engineer",
    location: "Pune, India", department: "Infrastructure", industry: "IT Services", isActive: true,
    overview: "Build and operate infrastructure that powers engineering systems.",
    aboutRole: "Champion automation and reliability across our cloud infrastructure.",
    description: "We need a DevOps Engineer experienced with AWS, Kubernetes, and CI/CD pipelines.",
    keyResponsibilities: ["Manage AWS infrastructure with Terraform", "Maintain Kubernetes clusters", "Build CI/CD pipelines", "Implement monitoring with Prometheus", "Conduct cost optimization"],
    responsibilities: "Ensure high availability and reliability of all systems.",
    skills: ["Docker", "Kubernetes", "AWS", "CI/CD", "Terraform"],
    preferredSkills: ["Helm", "ArgoCD", "Prometheus", "Grafana"],
    experienceRequired: "3-7 Years", experienceLevel: "Senior", education: "B.Tech in Computer Science or related field",
    type: "FULL_TIME", employmentType: "FULL_TIME", workMode: "HYBRID",
    priority: "High",
    salary: { min: 1400000, max: 2400000, currentCurrency: "INR" },
    salaryMin: 1400000, salaryMax: 2400000, salaryCurrency: "INR", salaryType: "ANNUAL",
    benefits: ["Health Insurance", "Stock Options", "Conference Sponsorship", "Flexible Hours"],
    visaSponsorship: false, postedAt: daysAgo(7), updatedAt: daysAgo(3),
  },
  {
    title: "Machine Learning Engineer",
    location: "Bangalore, India", department: "AI & ML", industry: "IT Services", isActive: true,
    overview: "Train and deploy ML models that power our intelligent features.",
    aboutRole: "Bridge the gap between research and production ML systems.",
    description: "Seeking an ML Engineer skilled in Python, TensorFlow, and MLOps to productionize models.",
    keyResponsibilities: ["Train production ML models", "Deploy models via FastAPI", "Implement A/B testing", "Manage ML lifecycle with MLflow", "Build feature pipelines"],
    responsibilities: "Own end-to-end ML model development and deployment.",
    skills: ["Python", "TensorFlow", "PyTorch", "Scikit-learn", "MLflow"],
    preferredSkills: ["Kubernetes", "FastAPI", "Feature Store", "ONNX"],
    experienceRequired: "3-6 Years", experienceLevel: "Senior", education: "Master's Degree preferred",
    type: "FULL_TIME", employmentType: "FULL_TIME", workMode: "HYBRID",
    priority: "High",
    salary: { min: 1800000, max: 3200000, currentCurrency: "INR" },
    salaryMin: 1800000, salaryMax: 3200000, salaryCurrency: "INR", salaryType: "ANNUAL",
    benefits: ["Health Insurance", "Stock Options", "Learning Budget", "Paid Time Off"],
    visaSponsorship: true, postedAt: daysAgo(4), updatedAt: daysAgo(1),
  },
  {
    title: "Data Engineer",
    location: "Mumbai, India", department: "Data", industry: "IT Services", isActive: true,
    overview: "Build data pipelines that power analytics and ML teams.",
    aboutRole: "Own the reliability and scalability of our data warehouse.",
    description: "Looking for a Data Engineer proficient in Python, Airflow, and Spark to build robust ETL pipelines.",
    keyResponsibilities: ["Build ETL pipelines with Airflow", "Maintain data warehouse in Snowflake", "Implement data quality checks", "Collaborate with data scientists", "Document data lineage"],
    responsibilities: "Design and maintain scalable data infrastructure.",
    skills: ["Python", "Apache Spark", "SQL", "Airflow", "AWS S3"],
    preferredSkills: ["dbt", "Snowflake", "Kafka", "BigQuery"],
    experienceRequired: "2-5 Years", experienceLevel: "Mid", education: "B.Tech in Computer Science or related field",
    type: "FULL_TIME", employmentType: "FULL_TIME", workMode: "HYBRID",
    priority: "Regular",
    salary: { min: 1000000, max: 1800000, currentCurrency: "INR" },
    salaryMin: 1000000, salaryMax: 1800000, salaryCurrency: "INR", salaryType: "ANNUAL",
    benefits: ["Health Insurance", "Annual Bonus", "Stock Options", "Free Meals"],
    visaSponsorship: false, postedAt: daysAgo(6), updatedAt: daysAgo(2),
  },
  {
    title: "QA Automation Engineer",
    location: "Chennai, India", department: "Quality", industry: "IT Services", isActive: true,
    overview: "Own the quality of our software through automated testing.",
    aboutRole: "Shift testing left and integrate QA into every CI/CD pipeline.",
    description: "We are hiring a QA Automation Engineer with strong skills in Cypress, Selenium, and Python.",
    keyResponsibilities: ["Write E2E tests with Cypress", "Build API tests with Postman", "Integrate tests in CI/CD", "Perform load testing with k6", "Triage and report bugs"],
    responsibilities: "Ensure software quality through automated test suites.",
    skills: ["Selenium", "Cypress", "Python", "Jest", "Postman"],
    preferredSkills: ["Playwright", "k6", "TestNG", "BDD"],
    experienceRequired: "2-5 Years", experienceLevel: "Mid", education: "B.Tech / B.E. in Engineering",
    type: "FULL_TIME", employmentType: "FULL_TIME", workMode: "ON_SITE",
    priority: "Regular",
    salary: { min: 700000, max: 1400000, currentCurrency: "INR" },
    salaryMin: 700000, salaryMax: 1400000, salaryCurrency: "INR", salaryType: "ANNUAL",
    benefits: ["Health Insurance", "Flexible Hours", "Learning Budget", "Paid Time Off"],
    visaSponsorship: false, postedAt: daysAgo(9), updatedAt: daysAgo(4),
  },
  {
    title: "iOS Developer",
    location: "Gurgaon, India", department: "Mobile", industry: "IT Services", isActive: true,
    overview: "Build polished iOS applications used by millions.",
    aboutRole: "Work in a fast-paced team with direct impact on millions of users.",
    description: "Looking for an experienced iOS Developer with strong Swift and SwiftUI skills.",
    keyResponsibilities: ["Develop iOS features in Swift", "Optimize app performance", "Integrate backend APIs", "Write XCTest unit tests", "Manage App Store releases"],
    responsibilities: "Develop and maintain high-quality iOS applications.",
    skills: ["Swift", "SwiftUI", "Xcode", "UIKit", "Core Data"],
    preferredSkills: ["Combine", "ARKit", "In-App Purchases", "Firebase"],
    experienceRequired: "2-5 Years", experienceLevel: "Mid", education: "Bachelor's Degree in any discipline",
    type: "FULL_TIME", employmentType: "FULL_TIME", workMode: "HYBRID",
    priority: "High",
    salary: { min: 1000000, max: 1800000, currentCurrency: "INR" },
    salaryMin: 1000000, salaryMax: 1800000, salaryCurrency: "INR", salaryType: "ANNUAL",
    benefits: ["Health Insurance", "Stock Options", "Flexible Hours", "Annual Bonus"],
    visaSponsorship: false, postedAt: daysAgo(10), updatedAt: daysAgo(5),
  },
  {
    title: "Android Developer",
    location: "Noida, India", department: "Mobile", industry: "IT Services", isActive: true,
    overview: "Build delightful Android apps from scratch.",
    aboutRole: "Work in a fast-paced team with direct impact on millions of users.",
    description: "Seeking an Android Developer proficient in Kotlin and Jetpack Compose.",
    keyResponsibilities: ["Implement UI with Jetpack Compose", "Manage app state with ViewModel", "Build data layers with Retrofit and Room", "Write unit tests", "Publish to Google Play"],
    responsibilities: "Develop and maintain Android applications.",
    skills: ["Kotlin", "Android SDK", "Jetpack Compose", "Retrofit", "Room"],
    preferredSkills: ["Coroutines", "Hilt", "Firebase", "Play Billing"],
    experienceRequired: "2-5 Years", experienceLevel: "Mid", education: "B.Tech in Computer Science or related field",
    type: "FULL_TIME", employmentType: "FULL_TIME", workMode: "ON_SITE",
    priority: "Regular",
    salary: { min: 900000, max: 1600000, currentCurrency: "INR" },
    salaryMin: 900000, salaryMax: 1600000, salaryCurrency: "INR", salaryType: "ANNUAL",
    benefits: ["Health Insurance", "Performance Bonus", "Free Meals", "Gym Membership"],
    visaSponsorship: false, postedAt: daysAgo(12), updatedAt: daysAgo(6),
  },
  {
    title: "Cybersecurity Analyst",
    location: "Mumbai, India", department: "Security", industry: "IT Services", isActive: true,
    overview: "Protect the organization's digital assets from threats.",
    aboutRole: "Be our last line of defense through proactive threat detection.",
    description: "Looking for a Cybersecurity Analyst with expertise in SIEM, penetration testing, and incident response.",
    keyResponsibilities: ["Monitor SIEM dashboards", "Conduct penetration tests", "Perform vulnerability assessments", "Respond to incidents", "Train developers on secure coding"],
    responsibilities: "Detect, respond to, and prevent cybersecurity threats.",
    skills: ["SIEM", "Penetration Testing", "OWASP", "Network Security", "Splunk"],
    preferredSkills: ["CEH", "CISSP", "Burp Suite", "Threat Modeling"],
    experienceRequired: "3-6 Years", experienceLevel: "Mid", education: "B.Tech in Computer Science or related field",
    type: "FULL_TIME", employmentType: "FULL_TIME", workMode: "HYBRID",
    priority: "Urgent",
    salary: { min: 1200000, max: 2200000, currentCurrency: "INR" },
    salaryMin: 1200000, salaryMax: 2200000, salaryCurrency: "INR", salaryType: "ANNUAL",
    benefits: ["Health Insurance", "Life Insurance", "Stock Options", "Learning Budget"],
    visaSponsorship: false, postedAt: daysAgo(1), updatedAt: daysAgo(1),
  },
  {
    title: "Site Reliability Engineer",
    location: "Bangalore, India", department: "Infrastructure", industry: "IT Services", isActive: true,
    overview: "Ensure reliability, scalability, and performance of production systems.",
    aboutRole: "Define and meet SLOs across the entire platform.",
    description: "Seeking an SRE experienced in Kubernetes, Python, incident management, and chaos engineering.",
    keyResponsibilities: ["Define SLIs and SLOs", "Build runbooks", "Conduct post-mortems", "Run chaos experiments", "Improve reliability by design"],
    responsibilities: "Maintain and improve the reliability of all production systems.",
    skills: ["Linux", "Python", "Kubernetes", "Prometheus", "Incident Management"],
    preferredSkills: ["Chaos Engineering", "SLO", "Terraform", "PagerDuty"],
    experienceRequired: "4-8 Years", experienceLevel: "Senior", education: "B.Tech / B.E. in Engineering",
    type: "FULL_TIME", employmentType: "FULL_TIME", workMode: "HYBRID",
    priority: "High",
    salary: { min: 1600000, max: 2800000, currentCurrency: "INR" },
    salaryMin: 1600000, salaryMax: 2800000, salaryCurrency: "INR", salaryType: "ANNUAL",
    benefits: ["Health Insurance", "Stock Options", "Conference Sponsorship", "Flexible Hours"],
    visaSponsorship: true, postedAt: daysAgo(8), updatedAt: daysAgo(3),
  },
  {
    title: "Technical Lead",
    location: "Hyderabad, India", department: "Engineering", industry: "IT Services", isActive: true,
    overview: "Lead a squad of engineers building world-class products.",
    aboutRole: "Balance hands-on coding with technical leadership and mentorship.",
    description: "Looking for a Tech Lead with 6+ years of experience in full-stack development and team leadership.",
    keyResponsibilities: ["Lead sprint planning", "Review code and enforce standards", "Design system architecture", "Mentor engineers", "Collaborate with product on roadmap"],
    responsibilities: "Lead technical execution and mentor the engineering team.",
    skills: ["System Design", "Code Review", "React", "Node.js", "Mentorship"],
    preferredSkills: ["AWS", "Agile", "Architecture", "TypeScript"],
    experienceRequired: "6-10 Years", experienceLevel: "Mid", education: "B.Tech in Computer Science or related field",
    type: "FULL_TIME", employmentType: "FULL_TIME", workMode: "HYBRID",
    priority: "High",
    salary: { min: 2200000, max: 3800000, currentCurrency: "INR" },
    salaryMin: 2200000, salaryMax: 3800000, salaryCurrency: "INR", salaryType: "ANNUAL",
    benefits: ["Health Insurance", "Stock Options", "Annual Bonus", "Learning Budget"],
    visaSponsorship: false, postedAt: daysAgo(5), updatedAt: daysAgo(2),
  },
  {
    title: "Blockchain Developer",
    location: "Remote", department: "Web3", industry: "IT Services", isActive: true,
    overview: "Build decentralized applications and smart contracts.",
    aboutRole: "Help shape the future of our Web3 platform.",
    description: "Seeking a Blockchain Developer proficient in Solidity, Web3.js, and smart contract auditing.",
    keyResponsibilities: ["Write and audit Solidity smart contracts", "Integrate with Web3.js", "Deploy to testnet and mainnet", "Implement DeFi protocols", "Write Hardhat tests"],
    responsibilities: "Build and maintain blockchain-based applications.",
    skills: ["Solidity", "Ethereum", "Web3.js", "Hardhat", "Smart Contracts"],
    preferredSkills: ["IPFS", "Chainlink", "Layer 2", "NFT Standards"],
    experienceRequired: "2-5 Years", experienceLevel: "Mid", education: "Bachelor's Degree in any discipline",
    type: "FULL_TIME", employmentType: "FULL_TIME", workMode: "REMOTE",
    priority: "Regular",
    salary: { min: 1400000, max: 2600000, currentCurrency: "INR" },
    salaryMin: 1400000, salaryMax: 2600000, salaryCurrency: "INR", salaryType: "ANNUAL",
    benefits: ["Home Office Stipend", "Stock Options", "Flexible Hours", "Learning Budget"],
    visaSponsorship: false, postedAt: daysAgo(14), updatedAt: daysAgo(7),
  },
  {
    title: "Cloud Architect",
    location: "Bangalore, India", department: "Architecture", industry: "IT Services", isActive: true,
    overview: "Define cloud strategy and architecture standards for the organization.",
    aboutRole: "Guide engineering teams in building scalable and secure cloud solutions.",
    description: "Looking for a Cloud Architect with expertise across AWS, Azure, and GCP.",
    keyResponsibilities: ["Design multi-cloud blueprints", "Define security standards", "Lead cloud migration projects", "Review architecture proposals", "Mentor senior engineers"],
    responsibilities: "Set cloud architecture direction across the organization.",
    skills: ["AWS", "Azure", "GCP", "Terraform", "Architecture Design"],
    preferredSkills: ["TOGAF", "Multi-cloud", "FinOps", "Security"],
    experienceRequired: "7-12 Years", experienceLevel: "Senior", education: "B.Tech / B.E. in Engineering",
    type: "FULL_TIME", employmentType: "FULL_TIME", workMode: "HYBRID",
    priority: "Urgent",
    salary: { min: 3000000, max: 5000000, currentCurrency: "INR" },
    salaryMin: 3000000, salaryMax: 5000000, salaryCurrency: "INR", salaryType: "ANNUAL",
    benefits: ["Health Insurance", "Stock Options", "Conference Sponsorship", "Annual Bonus"],
    visaSponsorship: true, postedAt: daysAgo(3), updatedAt: daysAgo(1),
  },
  {
    title: "Database Administrator",
    location: "Pune, India", department: "Engineering", industry: "IT Services", isActive: true,
    overview: "Manage and optimize databases that power our products.",
    aboutRole: "Ensure high availability, performance, and integrity of all databases.",
    description: "Seeking a DBA with expertise in PostgreSQL, MongoDB, and database performance tuning.",
    keyResponsibilities: ["Monitor and optimize query performance", "Maintain backup and DR plans", "Manage access controls", "Perform schema migrations", "Evaluate new database tech"],
    responsibilities: "Maintain and optimize all production databases.",
    skills: ["PostgreSQL", "MySQL", "MongoDB", "Query Optimization", "Backup & Recovery"],
    preferredSkills: ["Redis", "Cassandra", "AWS RDS", "pgAdmin"],
    experienceRequired: "3-7 Years", experienceLevel: "Senior", education: "B.Tech in Computer Science or related field",
    type: "FULL_TIME", employmentType: "FULL_TIME", workMode: "HYBRID",
    priority: "Regular",
    salary: { min: 1000000, max: 1800000, currentCurrency: "INR" },
    salaryMin: 1000000, salaryMax: 1800000, salaryCurrency: "INR", salaryType: "ANNUAL",
    benefits: ["Health Insurance", "Performance Bonus", "Flexible Hours", "Free Meals"],
    visaSponsorship: false, postedAt: daysAgo(11), updatedAt: daysAgo(5),
  },
  {
    title: "UI/UX Designer",
    location: "Remote", department: "Design", industry: "IT Services", isActive: true,
    overview: "Design intuitive and beautiful product experiences.",
    aboutRole: "Own the design process from research through to polished high-fidelity prototypes.",
    description: "Looking for a UI/UX Designer skilled in Figma, user research, and design systems.",
    keyResponsibilities: ["Conduct user research and usability tests", "Create wireframes and prototypes in Figma", "Build and maintain the design system", "Collaborate with engineers on implementation", "Present designs to stakeholders"],
    responsibilities: "Own the end-to-end design of product features.",
    skills: ["Figma", "User Research", "Prototyping", "Design Systems", "Usability Testing"],
    preferredSkills: ["Framer", "Motion Design", "Accessibility", "Data-Driven Design"],
    experienceRequired: "2-5 Years", experienceLevel: "Mid", education: "Bachelor's in Design or Fine Arts",
    type: "FULL_TIME", employmentType: "FULL_TIME", workMode: "REMOTE",
    priority: "Regular",
    salary: { min: 800000, max: 1600000, currentCurrency: "INR" },
    salaryMin: 800000, salaryMax: 1600000, salaryCurrency: "INR", salaryType: "ANNUAL",
    benefits: ["Home Office Stipend", "Health Insurance", "Paid Time Off", "Learning Budget"],
    visaSponsorship: false, postedAt: daysAgo(6), updatedAt: daysAgo(3),
  },
  {
    title: "Product Manager – SaaS",
    location: "Bangalore, India", department: "Product", industry: "IT Services", isActive: true,
    overview: "Define and execute product strategy for our SaaS platform.",
    aboutRole: "Work at the intersection of business, design, and engineering.",
    description: "Seeking a Product Manager with 4+ years of experience in B2B SaaS product management.",
    keyResponsibilities: ["Define product vision and roadmap", "Write PRDs and user stories", "Conduct user research", "Work with engineering in agile sprints", "Analyze product metrics"],
    responsibilities: "Own the product lifecycle from idea to launch.",
    skills: ["Product Management", "Agile", "User Research", "Roadmap Planning", "Analytics"],
    preferredSkills: ["SQL", "A/B Testing", "Mixpanel", "Figma"],
    experienceRequired: "4-8 Years", experienceLevel: "Senior", education: "MBA or Bachelor's in Engineering",
    type: "FULL_TIME", employmentType: "FULL_TIME", workMode: "HYBRID",
    priority: "High",
    salary: { min: 1800000, max: 3000000, currentCurrency: "INR" },
    salaryMin: 1800000, salaryMax: 3000000, salaryCurrency: "INR", salaryType: "ANNUAL",
    benefits: ["Health Insurance", "Stock Options", "Annual Bonus", "Conference Sponsorship"],
    visaSponsorship: false, postedAt: daysAgo(4), updatedAt: daysAgo(2),
  },
  {
    title: "React Native Developer",
    location: "Mumbai, India", department: "Mobile", industry: "IT Services", isActive: true,
    overview: "Build cross-platform mobile apps for iOS and Android.",
    aboutRole: "Own the mobile layer of our consumer-facing product.",
    description: "Looking for a React Native Developer experienced in building production-grade mobile apps.",
    keyResponsibilities: ["Build cross-platform features in React Native", "Integrate REST APIs and push notifications", "Optimize performance and reduce bundle size", "Write unit tests with Jest", "Submit builds to App Store and Play Store"],
    responsibilities: "Develop and maintain cross-platform mobile applications.",
    skills: ["React Native", "JavaScript", "TypeScript", "Redux", "REST APIs"],
    preferredSkills: ["Expo", "Firebase", "Detox", "Native Modules"],
    experienceRequired: "2-5 Years", experienceLevel: "Mid", education: "Bachelor's Degree in any discipline",
    type: "FULL_TIME", employmentType: "FULL_TIME", workMode: "HYBRID",
    priority: "Regular",
    salary: { min: 900000, max: 1600000, currentCurrency: "INR" },
    salaryMin: 900000, salaryMax: 1600000, salaryCurrency: "INR", salaryType: "ANNUAL",
    benefits: ["Health Insurance", "Flexible Hours", "Annual Bonus", "Free Meals"],
    visaSponsorship: false, postedAt: daysAgo(15), updatedAt: daysAgo(8),
  },
  {
    title: "Data Scientist",
    location: "Bangalore, India", department: "Data Science", industry: "IT Services", isActive: true,
    overview: "Build models that solve real business problems.",
    aboutRole: "Work with product and engineering to deliver ML-powered features.",
    description: "Seeking a Data Scientist with strong Python, statistics, and ML modelling skills.",
    keyResponsibilities: ["Build predictive models for business use cases", "Perform EDA and feature engineering", "Collaborate with data engineers on pipelines", "Present insights to stakeholders", "Run experiments and measure impact"],
    responsibilities: "Apply data science to drive measurable business outcomes.",
    skills: ["Python", "Machine Learning", "Statistics", "SQL", "Scikit-learn"],
    preferredSkills: ["Deep Learning", "NLP", "Spark", "MLflow"],
    experienceRequired: "2-5 Years", experienceLevel: "Mid", education: "Master's Degree preferred",
    type: "FULL_TIME", employmentType: "FULL_TIME", workMode: "HYBRID",
    priority: "High",
    salary: { min: 1400000, max: 2400000, currentCurrency: "INR" },
    salaryMin: 1400000, salaryMax: 2400000, salaryCurrency: "INR", salaryType: "ANNUAL",
    benefits: ["Health Insurance", "Stock Options", "Learning Budget", "Paid Time Off"],
    visaSponsorship: false, postedAt: daysAgo(7), updatedAt: daysAgo(3),
  },
  {
    title: "Scrum Master",
    location: "Chennai, India", department: "Delivery", industry: "IT Services", isActive: true,
    overview: "Facilitate agile ceremonies and remove blockers for the engineering team.",
    aboutRole: "Champion agile culture and continuous improvement across squads.",
    description: "Looking for a certified Scrum Master who can coach teams and drive agile adoption.",
    keyResponsibilities: ["Facilitate daily standups, sprint planning, and retrospectives", "Remove impediments for the team", "Track sprint metrics and velocity", "Coach teams on agile best practices", "Collaborate with product owners on backlog grooming"],
    responsibilities: "Enable high-performing agile teams to deliver great software.",
    skills: ["Scrum", "Agile", "JIRA", "Facilitation", "Stakeholder Management"],
    preferredSkills: ["SAFe", "Kanban", "Confluence", "Coaching"],
    experienceRequired: "3-7 Years", experienceLevel: "Senior", education: "Any Graduate",
    type: "FULL_TIME", employmentType: "FULL_TIME", workMode: "HYBRID",
    priority: "Regular",
    salary: { min: 1000000, max: 1800000, currentCurrency: "INR" },
    salaryMin: 1000000, salaryMax: 1800000, salaryCurrency: "INR", salaryType: "ANNUAL",
    benefits: ["Health Insurance", "Annual Bonus", "Flexible Hours", "Paid Time Off"],
    visaSponsorship: false, postedAt: daysAgo(20), updatedAt: daysAgo(10),
  },
];

async function seed() {
  try {
    const res = await prisma.job.createMany({
      data: jobs
    });
    console.log(`✅ seed1_it.js → Inserted ${res.count} IT Services jobs using Prisma`);
  } catch (error) {
    console.error('Seeding failed:', error.message);
  } finally {
    await prisma.$disconnect();
  }
}

seed();
